config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    
    # 名前
    validates :name, presence: true, length: { maximum: 50 }
    # email
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                       format: { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false }
    has_secure_password
    
    # area
    validates :area, presence: true, length: { maximum: 30 }, on: :update
    # profile
    validates :profile, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  #　ログイン処理
  def create
    # ユーザーをメールアドレスから検索します。
    @user = User.find_by(email: params[:session][:email].downcase)
    
    # もしユーザーが見つかった場合は、authenticateメソッドでパスワードが正しいか調べます。
    # パスワードが正しい場合は、session[:user_id]にユーザーIDを入れ、ユーザーの詳細ページにリダイレクトします。
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
      
      # パスワードが間違っている場合は’new’テンプレートを表示します。
      else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  
  
  #　ログアウト処理
  #　session[:user_id]をnilにしています。これでサーバーとブラウザの両方でセッションの情報が破棄されます。
  #  アプリケーションのルート/にリダイレクトします。
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]
  
  
  def show 
  end
 
  def new
    @user = User.new
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user # ここを修正
    else
      render 'new'
    end
  end
  
  def edit # 追加
  end
 
 
  def update # 追加
    if @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'your profile updated'
     else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user == @user
  end

  def user_params
    params.require(:user).permit(:name, :email, :area, :profile, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  # ||=は左の値がfalseかnilの場合に右の値の代入を行います。変数を初期化する際によく用いられます。
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # !!は、右側に続く値が存在する場合はtrueを、nilの場合はfalseを返します
  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %> <!-- ここから -->
           <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %> <!-- ここまで追加 -->
        <%= yield %>
       </div>
</body>
</html>


 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit</h1>

<div class="row">
    <%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 --> 


      <div class="form-group">
        <%= f.label :name, class: "col-xs-3 control-label", for: "user_name" %>
        <div class="col-xs-9">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>   
  
  　　<div class="form-group">
        <%= f.label :email, class: "col-xs-3 control-label", for: "user_email" %>
        <div class="col-xs-9">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>  
      
  　　<div class="form-group">
        <%= f.label :area, class: "col-xs-3 control-label", for: "user_area" %>
        <div class="col-xs-9">
          <%= f.text_field :area, class: "form-control" %>
        </div>
      </div>  
      
  　　<div class="form-group">
        <%= f.label :profile, class: "col-xs-3 control-label", for: "user_profile" %>
        <div class="col-xs-9">
          <%= f.text_area :profile, class: "form-control" %>
        </div>
      </div>  
      
  　　<div class="form-group">
        <%= f.label :password, class: "col-xs-3 control-label", for: "user_password" %>
        <div class="col-xs-9">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>  
      
  　　<div class="form-group">
        <%= f.label :password_confirmation, class: "col-xs-3 control-label", for: "user_password_confirmation" %>
        <div class="col-xs-9">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>  
      
      <div class="form-group">
       <div class="col-sm-offset-3 col-sm-9">
        <%= f.submit "送信", class: "btn btn-primary" %>
       </div>
      </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  
 
    <%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 --> 


      <div class="form-group">
        <%= f.label :name, class: "col-xs-3 control-label", for: "user_name" %>
        <div class="col-xs-9">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>   
  
  　　<div class="form-group">
        <%= f.label :email, class: "col-xs-3 control-label", for: "user_email" %>
        <div class="col-xs-9">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>  
      
  　　<div class="form-group">
        <%= f.label :password, class: "col-xs-3 control-label", for: "user_password" %>
        <div class="col-xs-9">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>  
      
  　　<div class="form-group">
        <%= f.label :password_confirmation, class: "col-xs-3 control-label", for: "user_password_confirmation" %>
        <div class="col-xs-9">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>  
      
      <div class="form-group">
       <div class="col-sm-offset-3 col-sm-9">
        <%= f.submit "送信", class: "btn btn-primary" %>
       </div>
      </div>
    <% end %>
</div>





   

app/views/users/show.html.erb
<h1>プロフィール</h1>
<!--  レスポンシブなテーブル　-->
<div class="table-responsive">
  <table class="table">
   <tr>
     <th><%= gravatar_for @user %></th>
       
   </tr>
   <tr>
     <th>名前</th>
     <th><%= @user.name %></th>
   </tr>
   <tr>
     <th>Eメール</th>
     <th><%= @user.email %></th>
   </tr>
   <tr>
     <th>地域</th>
     <th><%= @user.area %></th>
   </tr>
   <tr>
     <th>プロフィール</th>
     <th><%= @user.profile %></th>
   </tr>
  </table>
</div>